"""Add profile_picture to User model

Revision ID: 492888bc5a11
Revises: f5a9a0000716
Create Date: 2025-04-11 10:35:28.374886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492888bc5a11'
down_revision = 'f5a9a0000716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
