"""Add indexes to User, Job, Application models

Revision ID: 8758ee3d4118
Revises: 9e02d293eff0
Create Date: 2025-04-28 12:25:18.704492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8758ee3d4118'
down_revision = '9e02d293eff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_unique_constraint('_job_applicant_uc', ['job_id', 'applicant_id'])
        batch_op.create_index(batch_op.f('ix_application_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_application_date'), ['application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_status'), ['status'], unique=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_posted_date'), ['posted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_poster_id'), ['poster_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_poster_id'))
        batch_op.drop_index(batch_op.f('ix_job_posted_date'))
        batch_op.drop_index(batch_op.f('ix_job_location'))
        batch_op.drop_index(batch_op.f('ix_job_company'))
        batch_op.drop_index(batch_op.f('ix_job_category'))

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status'))
        batch_op.drop_index(batch_op.f('ix_application_job_id'))
        batch_op.drop_index(batch_op.f('ix_application_application_date'))
        batch_op.drop_index(batch_op.f('ix_application_applicant_id'))
        batch_op.drop_constraint('_job_applicant_uc', type_='unique')

    # ### end Alembic commands ###
