"""Add unique constraint to Job model

Revision ID: 90ad5652fc59
Revises: 3d33b12dc264
Create Date: 2025-04-10 07:35:14.224196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ad5652fc59'
down_revision = '3d33b12dc264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_job_title_company_poster', ['title', 'company', 'poster_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_title_company_poster', type_='unique')

    # ### end Alembic commands ###
