"""add_company_logo_to_job_model

Revision ID: cdb0771053c6
Revises: 492888bc5a11
Create Date: 2025-04-11 16:11:45.543565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb0771053c6'
down_revision = '492888bc5a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('company_logo')

    # ### end Alembic commands ###
