"""Add location to job uniqueness constraint

Revision ID: f5a9a0000716
Revises: 90ad5652fc59
Create Date: 2025-04-10 07:40:23.880352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a9a0000716'
down_revision = '90ad5652fc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_title_company_poster', type_='unique')
        batch_op.create_unique_constraint('uq_job_title_company_poster_location', ['title', 'company', 'poster_id', 'location'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_title_company_poster_location', type_='unique')
        batch_op.create_unique_constraint('uq_job_title_company_poster', ['title', 'company', 'poster_id'])

    # ### end Alembic commands ###
